substitutions:
  _SERVICE_NAME: streamlit-app
  _TAG: latest

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfiles/frontend.dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'