steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfiles/Dockerfile.backend'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fastapi-app:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fastapi-app:latest'